/**
 * Centralized error codes for structured API error responses.
 * These codes are machine-readable and used by the frontend to display
 * appropriate user-facing messages.
 *
 * Naming convention: DOMAIN_ACTION_REASON
 */
export enum ErrorCode {
  // ============================================
  // AUTHENTICATION & AUTHORIZATION
  // ============================================
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_PERMISSION_DENIED = 'AUTH_PERMISSION_DENIED',
  AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',
  AUTH_USER_LOGGED_OUT = 'AUTH_USER_LOGGED_OUT',
  AUTH_BAD_REQUEST = 'AUTH_BAD_REQUEST',

  // ============================================
  // USER & ACCOUNT
  // ============================================
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_EMAIL_NOT_FOUND = 'USER_EMAIL_NOT_FOUND',
  USER_PHONE_REQUIRED = 'USER_PHONE_REQUIRED',
  USER_MULTIPLE_PHONE_MATCHES = 'USER_MULTIPLE_PHONE_MATCHES',
  USER_ACCOUNT_EXISTS = 'USER_ACCOUNT_EXISTS',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_BLOCKED_TEMPORARY = 'USER_BLOCKED_TEMPORARY',
  USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',

  // ============================================
  // PASSWORD RESET
  // ============================================
  PASSWORD_USER_NOT_VERIFIED = 'PASSWORD_USER_NOT_VERIFIED',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
  PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD',
  PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_LINK_EXPIRED = 'PASSWORD_RESET_LINK_EXPIRED',

  // ============================================
  // VERIFICATION & REFERRALS
  // ============================================
  REFERRAL_CODES_REQUIRED = 'REFERRAL_CODES_REQUIRED',
  REFERRAL_CODES_MUST_DIFFER = 'REFERRAL_CODES_MUST_DIFFER',
  REFERRAL_CANNOT_USE_OWN = 'REFERRAL_CANNOT_USE_OWN',
  REFERRAL_USER_NOT_VERIFIED = 'REFERRAL_USER_NOT_VERIFIED',
  REFERRAL_SAME_USER = 'REFERRAL_SAME_USER',
  REFERRAL_CANNOT_VERIFY_SELF = 'REFERRAL_CANNOT_VERIFY_SELF',
  REFERRAL_GENDER_REQUIREMENT = 'REFERRAL_GENDER_REQUIREMENT',
  REFERRAL_NOT_FOUND = 'REFERRAL_NOT_FOUND',

  VERIFICATION_NOT_FOUND = 'VERIFICATION_NOT_FOUND',
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  VERIFICATION_REJECTED = 'VERIFICATION_REJECTED',
  VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED',
  VERIFICATION_VIDEO_UPLOAD_FAILED = 'VERIFICATION_VIDEO_UPLOAD_FAILED',

  // ============================================
  // FLAGSHIP / TRIPS
  // ============================================
  FLAGSHIP_NOT_FOUND = 'FLAGSHIP_NOT_FOUND',
  FLAGSHIP_INVALID_DATE_RANGE = 'FLAGSHIP_INVALID_DATE_RANGE',
  FLAGSHIP_FILE_UPLOAD_FAILED = 'FLAGSHIP_FILE_UPLOAD_FAILED',
  FLAGSHIP_QUERY_SEND_FAILED = 'FLAGSHIP_QUERY_SEND_FAILED',

  // ============================================
  // REGISTRATION
  // ============================================
  REGISTRATION_NOT_FOUND = 'REGISTRATION_NOT_FOUND',
  REGISTRATION_ID_REQUIRED = 'REGISTRATION_ID_REQUIRED',

  // ============================================
  // WAITLIST
  // ============================================
  WAITLIST_AUTH_REQUIRED = 'WAITLIST_AUTH_REQUIRED',
  WAITLIST_NOT_ACTIVE = 'WAITLIST_NOT_ACTIVE',
  WAITLIST_OFFER_MISSING = 'WAITLIST_OFFER_MISSING',
  WAITLIST_OFFER_EXPIRED = 'WAITLIST_OFFER_EXPIRED',
  WAITLIST_OFFER_STATE_CHANGED = 'WAITLIST_OFFER_STATE_CHANGED',
  WAITLIST_SEATS_FULL = 'WAITLIST_SEATS_FULL',
  WAITLIST_NOT_OWNER = 'WAITLIST_NOT_OWNER',

  // ============================================
  // CANCELLATION
  // ============================================
  CANCEL_AUTH_REQUIRED = 'CANCEL_AUTH_REQUIRED',
  CANCEL_NOT_ELIGIBLE = 'CANCEL_NOT_ELIGIBLE',
  CANCEL_STATE_CHANGED = 'CANCEL_STATE_CHANGED',
  CANCEL_NOT_OWNER = 'CANCEL_NOT_OWNER',

  // ============================================
  // PAYMENT
  // ============================================
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_NOT_OWNER = 'PAYMENT_NOT_OWNER',
  PAYMENT_USER_NOT_FOUND = 'PAYMENT_USER_NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_VALIDATION_FAILED = 'PAYMENT_VALIDATION_FAILED',

  // ============================================
  // REFUND
  // ============================================
  REFUND_AUTH_REQUIRED = 'REFUND_AUTH_REQUIRED',
  REFUND_REGISTRATION_NOT_FOUND = 'REFUND_REGISTRATION_NOT_FOUND',
  REFUND_NOT_OWNER = 'REFUND_NOT_OWNER',
  REFUND_REQUIRES_CONFIRMATION = 'REFUND_REQUIRES_CONFIRMATION',
  REFUND_REQUIRES_CANCELLATION = 'REFUND_REQUIRES_CANCELLATION',
  REFUND_ALREADY_REQUESTED = 'REFUND_ALREADY_REQUESTED',
  REFUND_PAYMENT_NOT_APPROVED = 'REFUND_PAYMENT_NOT_APPROVED',
  REFUND_FLAGSHIP_NOT_FOUND = 'REFUND_FLAGSHIP_NOT_FOUND',
  REFUND_CREDIT_ZERO = 'REFUND_CREDIT_ZERO',
  REFUND_FAILED = 'REFUND_FAILED',

  // ============================================
  // WALLET
  // ============================================
  WALLET_AUTH_REQUIRED = 'WALLET_AUTH_REQUIRED',
  WALLET_USER_ID_REQUIRED = 'WALLET_USER_ID_REQUIRED',
  WALLET_TX_NOT_FOUND = 'WALLET_TX_NOT_FOUND',
  WALLET_INSUFFICIENT_BALANCE = 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_VOID_INSUFFICIENT_BALANCE = 'WALLET_VOID_INSUFFICIENT_BALANCE',
  WALLET_INVALID_AMOUNT = 'WALLET_INVALID_AMOUNT',
  WALLET_TX_VOID = 'WALLET_TX_VOID',

  // ============================================
  // WALLET TOP-UP
  // ============================================
  TOPUP_AUTH_REQUIRED = 'TOPUP_AUTH_REQUIRED',
  TOPUP_ADMIN_AUTH_REQUIRED = 'TOPUP_ADMIN_AUTH_REQUIRED',
  TOPUP_NOT_FOUND = 'TOPUP_NOT_FOUND',
  TOPUP_ALREADY_PROCESSED = 'TOPUP_ALREADY_PROCESSED',

  // ============================================
  // NOTIFICATION
  // ============================================
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // ============================================
  // FEEDBACK
  // ============================================
  FEEDBACK_REGISTRATION_REQUIRED = 'FEEDBACK_REGISTRATION_REQUIRED',
  FEEDBACK_REGISTRATION_NOT_FOUND = 'FEEDBACK_REGISTRATION_NOT_FOUND',
  FEEDBACK_CREATE_FAILED = 'FEEDBACK_CREATE_FAILED',

  // ============================================
  // COMPANY PROFILE
  // ============================================
  COMPANY_PROFILE_NOT_FOUND = 'COMPANY_PROFILE_NOT_FOUND',
  COMPANY_PROFILE_REQUIRED_FIELDS = 'COMPANY_PROFILE_REQUIRED_FIELDS',
  COMPANY_PROFILE_LOGO_UPLOAD_FAILED = 'COMPANY_PROFILE_LOGO_UPLOAD_FAILED',
  COMPANY_PROFILE_SAVE_FAILED = 'COMPANY_PROFILE_SAVE_FAILED',

  // ============================================
  // MAIL
  // ============================================
  MAIL_RECIPIENT_REQUIRED = 'MAIL_RECIPIENT_REQUIRED',
  MAIL_CONFIG_MISSING = 'MAIL_CONFIG_MISSING',

  // ============================================
  // FAQ & RATING
  // ============================================
  FAQ_FETCH_FAILED = 'FAQ_FETCH_FAILED',
  FAQ_CREATE_FAILED = 'FAQ_CREATE_FAILED',
  RATING_FETCH_FAILED = 'RATING_FETCH_FAILED',

  // ============================================
  // GENERIC ERRORS
  // ============================================
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
